# Generated by Django 3.0.4 on 2020-03-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_bb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='price',
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='price_for_one',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='numb',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
